// Datos de posts embebidos como respaldo
const postsData = [
  {
    "id": 1,
    "featured": true,
    "tipo": "difusion",
    "category": "elecciones",
    "title": "Los lugares donde Jara podría ir a buscar votos para la segunda vuelta",
    "date": "Diciembre 1, de 2024",
    "author": "Matías Deneken",
    "authorLink": "#",
    "description": "Analizamos las comunas donde podrían haber más votantes potenciales comparando los resultados de las presidenciales y parlamentarias.",
    "link": "#",
    "image": "mapa"
  },
  {
    "id": 2,
    "featured": false,
    "tipo": "difusion",
    "category": "nacional",
    "title": "Tren al sur: los patrones de migración interna que nos revela el Censo 2024",
    "date": "Septiembre 2, de 2024",
    "author": "Matías Deneken",
    "authorLink": "#",
    "description": "Una mirada detallada a los datos nos dice que los habitantes migran a comunas más al sur que las de origen.",
    "link": "#",
    "image": "mapa"
  },
  {
    "id": 3,
    "featured": false,
    "tipo": "difusion",
    "category": "educación",
    "title": "¿De qué colegio saliste?",
    "date": "Abril 23, de 2024",
    "author": "Matías Deneken",
    "authorLink": "#",
    "description": "La mayoría del estudiantado en las universidades proviene de colegios particulares subvencionados, pero un grupo de 6 universidades se sale de la norma.",
    "link": "#",
    "image": "grafico"
  },
  {
    "id": 4,
    "featured": false,
    "tipo": "academico",
    "category": "género",
    "title": "La desigualdad a cada hora del día",
    "date": "Marzo 8, de 2024",
    "author": "Matías Deneken",
    "authorLink": "#",
    "description": "24 horas no alcanzan igual para todos: así se reparte el tiempo entre mujeres y hombres.",
    "link": "#",
    "image": "datos"
  },
  {
    "id": 5,
    "featured": false,
    "tipo": "academico",
    "category": "metodología",
    "title": "Métodos de inferencia causal en estudios observacionales de ciencias sociales",
    "date": "Noviembre 15, de 2024",
    "author": "Matías Deneken",
    "authorLink": "#",
    "description": "Revisión sistemática de técnicas avanzadas para establecer relaciones causales en datos no experimentales, incluyendo matching, diferencias en diferencias y regresión discontinua.",
    "link": "#",
    "image": "grafico"
  },
  {
    "id": 6,
    "featured": false,
    "tipo": "difusion",
    "category": "nacional",
    "title": "Análisis de la distribución geográfica de la pobreza en Chile",
    "date": "Mayo 12, de 2024",
    "author": "Matías Deneken",
    "authorLink": "#",
    "description": "Exploración de los patrones espaciales de pobreza utilizando datos del Censo y encuestas de hogares para identificar áreas de mayor concentración.",
    "link": "#",
    "image": "mapa"
  },
  {
    "id": 7,
    "featured": false,
    "tipo": "academico",
    "category": "metodología",
    "title": "Aplicación de métodos de machine learning en análisis de encuestas",
    "date": "Octubre 8, de 2024",
    "author": "Matías Deneken",
    "authorLink": "#",
    "description": "Evaluación comparativa de algoritmos de aprendizaje automático para predecir variables sociales complejas a partir de datos de encuestas.",
    "link": "#",
    "image": "datos"
  },
  {
    "id": 8,
    "featured": false,
    "tipo": "difusion",
    "category": "educación",
    "title": "La brecha de género en carreras STEM: evidencia desde los datos",
    "date": "Agosto 20, de 2024",
    "author": "Matías Deneken",
    "authorLink": "#",
    "description": "Análisis de la representación de mujeres en carreras de ciencia, tecnología, ingeniería y matemáticas en universidades chilenas.",
    "link": "#",
    "image": "grafico"
  },
  {
    "id": 9,
    "featured": false,
    "tipo": "academico",
    "category": "metodología",
    "title": "Diseño de experimentos naturales en ciencias sociales",
    "date": "Julio 15, de 2024",
    "author": "Matías Deneken",
    "authorLink": "#",
    "description": "Metodología para identificar y aprovechar experimentos naturales en estudios de ciencias sociales, con aplicaciones en políticas públicas.",
    "link": "#",
    "image": "mapa"
  },
  {
    "id": 10,
    "featured": false,
    "tipo": "difusion",
    "category": "nacional",
    "title": "Patrones de movilidad urbana durante la pandemia",
    "date": "Junio 5, de 2024",
    "author": "Matías Deneken",
    "authorLink": "#",
    "description": "Análisis de datos de movilidad para entender cómo cambió el comportamiento de desplazamiento en las principales ciudades de Chile.",
    "link": "#",
    "image": "datos"
  },
  {
    "id": 11,
    "featured": false,
    "tipo": "academico",
    "category": "metodología",
    "title": "Validación cruzada en modelos de regresión para datos sociales",
    "date": "Mayo 28, de 2024",
    "author": "Matías Deneken",
    "authorLink": "#",
    "description": "Técnicas avanzadas de validación cruzada aplicadas a modelos de regresión en contextos de datos sociales con estructura compleja.",
    "link": "#",
    "image": "grafico"
  },
  {
    "id": 12,
    "featured": false,
    "tipo": "difusion",
    "category": "género",
    "title": "Representación política de mujeres en elecciones locales",
    "date": "Abril 10, de 2024",
    "author": "Matías Deneken",
    "authorLink": "#",
    "description": "Análisis de los resultados electorales para evaluar el impacto de las cuotas de género en la representación política a nivel municipal.",
    "link": "#",
    "image": "mapa"
  },
  {
    "id": 13,
    "featured": false,
    "tipo": "academico",
    "category": "metodología",
    "title": "Análisis de redes sociales aplicado a estudios de comportamiento",
    "date": "Marzo 22, de 2024",
    "author": "Matías Deneken",
    "authorLink": "#",
    "description": "Aplicación de análisis de redes sociales para estudiar la difusión de información y comportamientos en grupos sociales.",
    "link": "#",
    "image": "datos"
  },
  {
    "id": 14,
    "featured": false,
    "tipo": "difusion",
    "category": "educación",
    "title": "Desigualdades en el acceso a educación superior",
    "date": "Febrero 18, de 2024",
    "author": "Matías Deneken",
    "authorLink": "#",
    "description": "Análisis de las barreras de acceso a la educación superior según nivel socioeconómico y tipo de establecimiento de origen.",
    "link": "#",
    "image": "grafico"
  },
  {
    "id": 15,
    "featured": false,
    "tipo": "academico",
    "category": "metodología",
    "title": "Métodos bayesianos en análisis de datos longitudinales",
    "date": "Enero 25, de 2024",
    "author": "Matías Deneken",
    "authorLink": "#",
    "description": "Aplicación de métodos bayesianos para el análisis de datos longitudinales en estudios de ciencias sociales con múltiples mediciones temporales.",
    "link": "#",
    "image": "mapa"
  }
];
